### ISSUE TITLE
fails if there are no parts

### ISSUE THREAD

**Issue by jbenet** [connrs/node-sandwich-stream#1]
There is a problem where sandwich-stream fails if no sub-streams have been added. while this is a reasonable API, it makes dependent modules harder to use, because now they must catch this error. 

I think it should be a no-op, like `ls` in an empty directory.

See https://github.com/hendrikcech/multipart-stream/issues/1 for reference.

---

@jbenet said

> ``` js
> > var mps = require('multipart-stream')
> > var m = new Multipart('wellhellotherehowsitgoing')
> > var m = new mps('wellhellotherehowsitgoing')
> > m.pipe(process.stdout)
> Error: SandwichStream no streams added error
>   at Multipart.SandwichStream._read (/Users/jbenet/git/node-vinyl-to-multipart-stream/node_modules/multipart-stream/node_modules/sandwich-stream/lib/sandwich-stream.js:30:24)
>  at Multipart.Readable.read (_stream_readable.js:324:10)
>  at resume_ (_stream_readable.js:705:12)
>  at doNTCallback2 (node.js:430:9)
>  at process._tickDomainCallback (node.js:385:17)
> ```
> 
> I would expect the body to just be empty, not throw.
> 
> multipart libraries differ on what to do here. many http libs/servers allow a multipart in an HTTP request with no parts. docs differ in whether this is allowed.

---

@hendrikcech said:

> This module inherits from connrs/node-sandwich-stream so this has to fixed / changed downstream. The error is thrown on [line 30](https://github.com/connrs/node-sandwich-stream/blob/master/lib/sandwich-stream.js#L30).
> Would you mind creating another issue there?

**Comment by connrs** [comment]
Hey @jbenet,

I'm more than happy to alter the functionality. It does seem a little bit extreme and isn't really something that the module really needs to function. I think that it just made sense when I wrote it at the time.

It's just a case of removing the test [here](https://github.com/connrs/node-sandwich-stream/blob/ff86e0e28a1aebd855aca1fd3da6cc9b0b2d0352/test/sandwich-stream.js#L5-L12) and the code [here](https://github.com/connrs/node-sandwich-stream/blob/ff86e0e28a1aebd855aca1fd3da6cc9b0b2d0352/lib/sandwich-stream.js#L29-L32).

I'll bump the version number as well (1.0.0) as it's a notable change. However, it'll be the only substantial change. The package.json references `^0.0.4` so this will need updating to pull down `^1.0.0` instead I'm afraid.

Thanks,
Paul.

**Comment by connrs** [comment]
Hi @jbenet,

I've just published version 1.0.0 for you. If you could update @hendrikcech about the version bump, I'm sure that you'll be back up and running in no time!

Thanks,
Paul.

**Comment by jbenet** [comment]
Thank you @connrs :)
