### ISSUE TITLE
Object not exported

### ISSUE THREAD

**Issue by negezor** [connrs/node-sandwich-stream#4]
After upgrading to version 2, the object is not returned
```js
$ node
> require('./node_modules/sandwich-stream/package.json').version
'2.0.0'
> require('sandwich-stream')
{}
```
Perhaps all the same it is better to use [rollup](https://github.com/rollup/rollup) instead of webpack?

**Comment by connrs** [comment]
I suspect that I've done something wrong when publishing 2.0.0 to npm. This new version was generously contributed by another developer and I haven't been an active node developer in several years so I'm a little out of practice.

I'll get a 2.0.1 released as soon as I understand the issue.

**Comment by connrs** [comment]
When I was actively developing on node.js, browserify was still **the** tool for packaging and transpilation was quite different too. Webpack seems very powerful but also very complex.

Sadly, the CI tests didn't test for the npm release containing a valid SandwichStream object so when Webpack was configured and happened to not export anything meaningful nothing was noticed!

I went to bed late last night having taken a crash course in Webpack + Typescript configuration. At the end of it I still know nothing about Webpack + Typescript configuration but hopefully, https://github.com/connrs/node-sandwich-stream/commit/90dbc8ccac73dd7ca8aab94dbeca3d0893581bcb resolves it.

I've published 2.0.1 to npm so could you let me know if you continue to have issues? If not please let me know and I'll close this issue down.

**Comment by negezor** [comment]
Because of the webpack bundle, this is happening.
```js
$ node
> require('sandwich-stream')
{ SandwichStream: [Function: SandwichStream],
  default: [Function: SandwichStream] }
> new require('sandwich-stream').SandwichStream
[Function: SandwichStream]
> new (new require('sandwich-stream').SandwichStream)({})
SandwichStream {
  _readableState:
   ReadableState {
```
I did a pull request that should fix this and above all add support for ESM https://github.com/connrs/node-sandwich-stream/pull/5.

**Comment by connrs** [comment]
Thank you for the PR changing to Rollup. I was considering asking you for a PR for this so you've saved me the trouble!

I've merged this in to a staging branch so I can get it built and tested first.

I'm happy that it's running in a node environment and I'm ready to publish to npm. Are you happy that your PR does all that you need or is there anything outstanding that you feel needs fixing?

**Comment by negezor** [comment]
I have already checked, it works for me. I think you can publish.

**Comment by connrs** [comment]
Thank you!
